config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}



  root 'public/homes#top'
  get 'about' => 'public/homes#about'

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
  end

  scope module: :public do
    delete 'destroy_all' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get  'finish'
      end
  end
    resource  :customers, only: [ :show, :edit, :update] do

      get 'confirm'
      patch 'withdrawal'


       collection do
        get 'quit'
        patch 'out'
      end
    end
  end

   devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    
  belongs_to :customer

  

  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  validates :customer_id, :item_id, :quantity, presence: true
  validates :quantity, numericality: { only_integer: true }
  
   def subtotal
    item.add_tax_price*quantity
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end
	
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :orders, through: :order_items
  has_many :order_items
  
  has_one_attached :image
  validates :genre_id, :name, :price, presence: true
	validates :body, length: { maximum: 200 }, presence: true
	validates :price, numericality: { only_integer: true }

def add_tax_price
  (self.price * 1.10).round
end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy #order_itemになってました

  #enum payment_method ["クレジットカード", "銀行振込"] #0=クレカ、1=銀行振り込み
  enum pay_method: { credit_card: 0, transfer: 1 }

  enum order_status: {
     "入金待ち": 0,
     "入金確認": 1,
     "製作中": 2,
     "発送準備中": 3,
     "発送済み": 4
  }


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  #ApplicationRecorhasになってました
  belongs_to :order #belongs_to :ordrerになってました
  belongs_to :item

enum creat_status: { #本来、create_statusです
  "着手不可":0,
  "制作待ち":1,
  "製作中":2,
  "制作完了":3,
}

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を変更しました"
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_kana_name, :last_kana_name, :postcode, :address, :phone_number, :email, :customer_status)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
   before_action :authenticate_admin!
   
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def create
   @genre = Genre.new(genre_params)
   @genres = Genre.all
   if @genre.save
      redirect_to admin_genres_path
   else
      render :index
   end
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def create
   @item = Item.new(item_params)
   @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def update
   @item = Item.find(params[:id])
   @genres = Genre.all
   if @item.update(item_params)
    redirect_to admin_item_path(@item)
   else
    render :edit
   end
  end

  private
  def item_params
   params.require(:item).permit(:name, :body, :genre_id, :price, :image, :sale_status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index #注文履歴一覧画面
     @orders = Order.all
  end

  def current_user_order
    @orders = Order.where(customer_id: params[:id])
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def update #注文ステータス更新
    @order = Order.find(params[:id])
    @order.update(order_params)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postcode, :address, :price, :order_status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_kana_name, :last_kana_name, :postcode, :address, :phone_number])
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row mb-5">
    <div class="offset-1">
      <h2 class="my-4 text title-sub-text"><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h2>
    </div>
    
    <div class="col-12">
      <%= form_with model: @customer, url: admin_customer_path, local:true do |f| %>
      
        <div class="form-group row text">
          <%= f.label :id, "会員ID", class: "col-form-label col-3 font-weight-bold" %>
          <div class="col=8 light-text">
           <%= f.label :id, @customer.id, class: "ml-4"  %>
          </div>
        </div>

        <div class="form-group row text">
          <%= f.label :first_name, "氏名", class: "col-form-label col-3 font-weight-bold" %>
          <div class="col-4 light-text">
            <%= f.text_field :last_name, class: "form-control" %>
          </div>
          <div class="col-4 light-text">
            <%= f.text_field :first_name, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row text">
          <%= f.label :first_name, "フリガナ", class: "col-form-label col-3 font-weight-bold" %>
          <div class="col-4 light-text">
            <%= f.text_field :last_kana_name, class: "form-control" %>
          </div>
          <div class="col-4 light-text">
            <%= f.text_field :first_kana_name, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row text">
          <%= f.label :postcode, "郵便番号", class: "col-form-label col-3 font-weight-bold" %>
          <div class="col-4 light-text">
            <%= f.text_field :postcode, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row text">
          <%= f.label :address, "住所", class: "col-form-label col-3 font-weight-bold" %>
          <div class="col-4 light-text">
            <%= f.text_field :address, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row text">
          <%= f.label :phone_number, "電話番号", class: "col-form-label col-3 font-weight-bold" %>
          <div class="col-4 light-text">
            <%= f.text_field :phone_number, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row text">
          <%= f.label :email, "メールアドレス", class: "col-form-label col-3 font-weight-bold" %>
          <div class="col-4 light-text">
            <%= f.email_field :email, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row text">
          <%= f.label :is_deleted, "会員ステータス", class: "col-form-label col-3 font-weight-bold" %>
          <div class="col-8 light-text">
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_deleted, false, class: "form-check-input" %>
              <%= f.label :is_deleted, "有効", value: false, class: "form-check-label" %>
            </div>
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_deleted, true, class: "form-check-input" %>
              <%= f.label :is_deleted, "退会", value: true, class: "form-check-label" %>
            </div>
          </div>
        </div>

        <div class="form-group row mt-2">
          <div class="col-3"></div>
          <div class="col-4 text">
            <%= f.submit "変更を保存", class: "btn btn-success w-50" %>
          </div>
        </div>

      <% end %>
      
      </div>

  </div>

</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row mb-4">
    <div class="col-12">
      <h3 class="offset-1 my-5 text title-text">会員一覧</h3>
      <div class="row">
        <div class="col-12 mx-auto">
          <table class="table table-hover">
            <thead>
              <tr class="table-active text">
                <th>会員ID</th>
                <th>氏名</th>
                <th>メールアドレス</th>
                <th>ステータス</th>
              </tr>
            </thead>

              <tbody>
                <% @customers.each do |customer| %>
                  <tr class="light-text">
                    <td><%= customer.id %></th>
                    <td class="text">
                      <%= link_to admin_customer_path(customer), class: "text-dark" do %>
                        <%= customer.last_name + customer.first_name %>
                      <% end %>
                    </td>
                    <td>
                      <%= customer.email %>
                    </td>
                    <td>
                      <% if customer.is_deleted %>
                    <span>退会</span>
                      <% else %>
                        <span class="text-success text">有効</span>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
           </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mb-5">
    <div class="offset-1">
      <h2 class="my-4 text title-sub-text"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
    </div>
    <div class="col-12">
      <table class="table table-borderless">
        <tr>
          <th class="w-25 text">会員ID</th>
          <td class="light-text"><%= @customer.id %></td>
        </tr>
        <tr>
          <th class="text">氏名</th>
          <td class="light-text"><%= @customer.last_name + @customer.first_name %></td>
        </tr>
        <tr>
          <th class="text">フリガナ</th>
          <td class="light-text"><%= @customer.last_kana_name + @customer.first_kana_name %></td>
        </tr>
        <tr>
          <th class="text">郵便番号</th>
          <td class="light-text"><%= @customer.postcode %></td>
        </tr>
        <tr>
          <th class="text">住所</th>
          <td class="light-text"><%= @customer.address %></td>
        </tr>
        <tr>
          <th class="text">電話番号</th>
          <td class="light-text"><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <th class="text">メールアドレス</th>
          <td class="light-text"><%= @customer.email %></td>
        </tr>
        <tr>
          <th class="text">会員ステータス</th>
          <td class="text">
            <% if @customer.is_deleted %>
              <span>退会</span>
            <% else %>
              <span class="text-success">有効</span>
            <% end %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td class="text">
            <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success mr-4 col-2" %>
            <%= link_to "注文履歴一覧を見る", admin_orders_path(@customer), class: "btn btn-primary ml-5 col-2" %>
          </td>
         </tr>
     </table>
  </div>