config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}



  root 'public/homes#top'
  get 'about' => 'public/homes#about'

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
  end

  scope module: :public do
    delete 'destroy_all' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get  'finish'
      end
  end
    resource  :customers, only: [ :show, :edit, :update] do

      get 'confirm'
      patch 'withdrawal'


       collection do
        get 'quit'
        patch 'out'
      end
    end
  end

   devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    
  belongs_to :customer

  

  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  validates :customer_id, :item_id, :quantity, presence: true
  validates :quantity, numericality: { only_integer: true }
  
   def subtotal
    item.add_tax_price*quantity
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end
	
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :orders, through: :order_items
  has_many :order_items
  
  has_one_attached :image
  validates :genre_id, :name, :price, presence: true
	validates :body, length: { maximum: 200 }, presence: true
	validates :price, numericality: { only_integer: true }

def add_tax_price
  (self.price * 1.10).round
end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy #order_itemになってました

  #enum payment_method ["クレジットカード", "銀行振込"] #0=クレカ、1=銀行振り込み
  enum pay_method: { credit_card: 0, transfer: 1 }

  enum order_status: {
     "入金待ち": 0,
     "入金確認": 1,
     "製作中": 2,
     "発送準備中": 3,
     "発送済み": 4
  }


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  #ApplicationRecorhasになってました
  belongs_to :order #belongs_to :ordrerになってました
  belongs_to :item

enum creat_status: { #本来、create_statusです
  "着手不可":0,
  "制作待ち":1,
  "製作中":2,
  "制作完了":3,
}

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
   before_action :authenticate_admin!
   
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def create
   @genre = Genre.new(genre_params)
   @genres = Genre.all
   if @genre.save
      redirect_to admin_genres_path
   else
      render :index
   end
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def create
   @item = Item.new(item_params)
   @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def update
   @item = Item.find(params[:id])
   @genres = Genre.all
   if @item.update(item_params)
    redirect_to admin_item_path(@item)
   else
    render :edit
   end
  end

  private
  def item_params
   params.require(:item).permit(:name, :body, :genre_id, :price, :image, :sale_status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index #注文履歴一覧画面
     @orders = Order.all
  end

  def current_user_order
    @orders = Order.where(customer_id: params[:id])
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def update #注文ステータス更新
    @order = Order.find(params[:id])
    @order.update(order_params)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postcode, :address, :price, :order_status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  
  # protected
  def after_sign_in_path_for(resource) #追加
    admin_orders_path
  end
  
  def after_sign_out_path_for(resource)
    admin_items_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_kana_name, :last_kana_name, :postcode, :address, :phone_number])
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container pt-5">
    <div class="row">
        <div class="col-12">
            <div class="d-flex mb-4">
            <h5 class="bg-light">ジャンル編集</h5>
            </div>
        </div>
        <div class="col-12">
         <%= form_with model: @genre, url: admin_genre_path, class: "d-flex align-items-center" do |f| %>
         <%= render 'layouts/errors', model: f.object %></br>
          <div class="pl-3"><%= f.label :name, "ジャンル名", class: "small" %></div>
          <div class="pl-3"><%= f.text_field :name, placeholder: "ジャンル名" %></div>
          <div class="ml-5"><%= f.submit "変更を保存", class: "btn btn-success ml-5" %></div>
         <% end %>
        </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container pt-5">
    <div class="row">
        <div class="col-12">
            <div class="d-flex mb-4">
            <h5 class="bg-light">ジャンル一覧・追加</h5>
            </div>
        </div>
        <div class="col-12">
         <%= form_with model: @genre, url: admin_genres_path, class: "d-flex align-items-center" do |f| %>
         <%= render 'layouts/errors', model: f.object %></br>
          <div class="pl-3"><%= f.label :name, "ジャンル名", class: "small" %></div>
          <div class="pl-3"><%= f.text_field :name, placeholder: "ジャンル名" %></div>
          <div class="ml-5"><%= f.submit "新規登録", class: "form-control btn btn-success ml-5" %></div>
         <% end %>
        </div>
        <div class="col-12 col-lg-5">
         <table class="table mt-5">
             <thead>
                 <tr class="bg-light">
                     <th class="pl-5">ジャンル</th>
                     <th></th>
                 </tr>
             </thead>
             <tbody>
                 <% @genres.each do |genre| %>
                 <tr>
                     <td><%= genre.name %></td>
                     <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success" %></td>
                 </tr>
                 <% end %>
             </tbody>
         </table>
        </div>
    </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h3 class="bg-light">商品編集</h3></br>
      <%= form_with model: @item, url: admin_item_path(@item), method: :patch, local:true do |f| %>
      <%= render 'layouts/errors', model: f.object %>
       <div class="form-group", style="display:inline-flex">
         <%= f.label "商品画像", class:"col-3" %>
         <%= f.file_field :image, accept: "image/*" %>
       </div>
       <div class="form-group">
         <%= f.label "商品名", class:"col-sm-3" %>
         <%= f.text_field :name %>
       </div>
       <div class="form-group">
         <%= f.label "商品説明", class:"col-sm-3" %>
         <%= f.text_area :body %>
       </div>
       <div class="form-group">
         <%= f.label "ジャンル", class:"col-sm-3" %>
         <%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "-- 選択してください --") %>
       </div>
       <div class="form-group">
         <%= f.label "税抜き価格", class:"col-sm-3" %>
         <%= f.text_field :price, :placeholder => "1000" %>円
       </div>
       <div class="form-group">
         <%= f.label "販売ステータス", class:"col-sm-4" %>
         <label><%= f.radio_button :sale_status, "true", checked: true %>販売中</label>
         <label style="margin-left: 30px;"><%= f.radio_button :sale_status, "false", checked: false %>販売停止中</label>
       </div>
       
       <div class="text-center">
         <%= f.submit :変更を保存, class:'btn btn-lg btn-success' %>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-12 mx-auto">
      <h2>商品一覧</h2>
      <div class="text-right">
      <%= link_to new_admin_item_path do %>
      <i class="fas fa-plus"></i>
      <% end %>

      </div>
      <% unless @items.blank? %>
       <table class='table mt-3'>
         <thead>
           <th>商品ID</th>
           <th>商品名</th>
           <th>税抜価格</th>
           <th>ジャンル</th>
           <th>ステータス</th>
         </thead>
         <tbody>
           <% @items.each do |item| %>
           <tr>
             <td><%= item.id %></td>
             <td><%= link_to item.name, admin_item_path(item) %></td>
             <td><%= item.price.to_s(:delimited) %></td>
             <td><%= item.genre.name %></td>
             <td>
               <% if item.sale_status == true %>
                <p class="text-success">販売中</p>
               <% elsif item.sale_status == false %>
                <p class="text-muted">販売停止中</p>
               <% end %>
             </td>
           </tr>
           <% end %>
         </tbody>
       </table>
       <% else %>
        <p>商品はありません</p>
       <% end %>

      <div class= "d-flex justify-content-center">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h3 class="bg-light">商品新規登録</h3></br>
      <%= form_with model: @item, url: admin_items_path, method: :post, local:true do |f| %>
      <%= render 'layouts/errors', model: f.object %>
       <div class="form-group" style="display:inline-flex">
         <%= f.label "商品画像", class:"col-3" %>
         <%= f.file_field :image, accept: "image/*" %>
       </div>
       <div class="form-group">
         <%= f.label "商品名", class:"col-sm-3" %>
         <%= f.text_field :name %>
       </div>
       <div class="form-group">
         <%= f.label "商品説明", class:"col-sm-3" %>
         <%= f.text_area :body %>
       </div>
       <div class="form-group">
         <%= f.label "ジャンル", class:"col-sm-3" %>
         <%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "-- 選択してください --") %>
       </div>
       <div class="form-group">
         <%= f.label "税抜き価格", class:"col-sm-3" %>
         <%= f.text_field :price, :placeholder => "1000" %>円
       </div>
       <div class="form-group">
         <%= f.label "販売ステータス", class:"col-sm-4" %>
         <label><%= f.radio_button :sale_status, "true", checked: true %>販売中</label>
         <label style="margin-left: 30px;"><%= f.radio_button :sale_status, "false", checked: false %>販売停止中</label>
       </div>

       <div class="text-center">
         <%= f.submit :新規登録, class:'btn btn-lg btn-success' %>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class= "container pt-5">
  <div class= "row">
    <div class="col-5">
      <h3 class="bg-light">商品詳細</h3>
      <div class="item-image", style="margin-top: 60px">
      <%= image_tag @item.image, size: "400x300" %></div>
    </div>
    <div class="col-7" style="margin-top: 90px;">
      <div>
        <label class="col-4">商品名</label>
        <%= @item.name %>
      </div>
      <div>
        <label class="col-4">商品説明</label>
        <%= @item.body %>
      </div>
      <div>
        <label class="col-4">ジャンル</label>
        <%= @item.genre.name %>
      </div>
      <div>
        <label class="col-4 h7">
          税込価格</br>(税抜価格)
        </label>
        <span><%= @item.add_tax_price.to_s(:delimited) %></span>
        <span>(<%= @item.price %>) 円</span>
      </div>
      
      <div>
        <label class="col-4">販売ステータス</label>
        <% if @item.sale_status == true %>
        <span class="text-success">販売中</span>
        <% elsif @item.sale_status == false %>
        <span class="text-muted">販売停止中</span>
        <% end %>
      </div>
    
    <div style="margin-top:60px;">
      <%= link_to "編集する", edit_admin_item_path(@item), class:"btn btn-lg btn-success" %></td>
    </div>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container my-5">
  <%#= render "shared/flash_message" %><!--消しました-->
  <div class="row">
    <div class="offset-1 text-center">
      <h3 class="title-text text">
        注文履歴一覧
      </h3>
    </div>
  </div>
  <div class="row mt-5">
    <table class="table table-hover">
      <thead>
        <tr class="table-active text">
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr class="light-text">
          <td>
            <%= link_to admin_order_path(order), class: "text-dark" do %>
              <%= order.created_at.strftime('%Y年/%m月/%d日 %H:%M:%S') %>
            <% end %>
          </td>
          <td>
            <%= order.customer.last_name %>
            <%= order.customer.first_name %>
          </td>
          <td><%= order.order_items.sum(:quanity) %></td>
          <td><%= order.order_status %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination"><%#= paginate @orders, theme: 'twitter-bootstrap-4' %></div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-1 text-center">
      <h3 class="title-sub-text text">
        注文履歴詳細
      </h3>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-9">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td class="table-active text">購入者</td>
            <td class="light-text">
              <%= link_to @order.name, admin_customer_path(@order.customer), class: "text-dark" %>
            </td>
          </tr>
          <tr>
            <td class="table-active text">注文日</td>
            <td class="light-text"><%= @order.created_at.strftime('%Y年/%m月/%d日') %></td>
          </tr>
          <tr>
            <td class="table-active text">配送先</td>
            <td class="light-text">
              〒<%= @order.postcode %><br>
                <%= @order.address %><br>
                <%= @order.name %> 様
            </td>
          </tr>
          <tr>
            <td class="table-active text">支払方法</td>
            <td class="light-text"><%= @order.pay_method %></td>
          </tr>
          <tr>
            <td class="table-active text">注文ステータス</td>
            <td class="light-text">
              <%= form_with model: @order, url: admin_order_path(@order), local: true,method: :patch do |f| %>
                <%= f.select :order_status, [["入金待ち", "入金待ち"], ["入金確認","入金確認"],["製作中","製作中"],["発送準備中","発送準備中"],["発送済み","発送済み"]], class: "form-control" %>
                <%= f.submit "更新", class: "btn btn-primary btn-sm" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-9">
      <table class="table table-borderless table-hover">
        <thead class="table-active">
          <tr class="text">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>個数</th>
            <th>小計</th>
            <th>制作ステータス</th>
          </tr>
        </thead>
        <tbody>
<% @order.order_items.each do |order_item| %>
          <tr class="light-text">
            <td><%= order_item.item.name %></td>
            <td><%= order_item.tax_price %></td>
            <td><%= order_item.quanity %></td>
            <td><%= order_item.tax_price * order_item.quanity %></td>
            <td>
              <%#= form_with model: order_item, local: true, method: :patch do |f| %>
                <%#= f.select :product_status, [["着手不可", "着手不可"], ["製作待ち","製作待ち"],["製作中","製作中"],["製作完了","製作完了"]], class: "form-control" %>
              　<%#= f.submit "更新", class: "btn btn-primary btn-sm" %>
              <%# end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-3">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td class="table-active text">商品合計</td>
            <td class="light-text">
              <%= @order.fare %></td>
          </tr>
          <tr>
            <td class="table-active text">請求合計金額</td>
            <td class="light-text"><%= @order.total_price %></td><!--total_moneyから変更-->
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>