config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}



  root 'public/homes#top'
  get 'about' => 'public/homes#about'

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
  end

  scope module: :public do
    delete 'destroy_all' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get  'finish'
      end
  end
    resource  :customers, only: [ :show, :edit, :update] do

      get 'confirm'
      patch 'withdrawal'


       collection do
        get 'quit'
        patch 'out'
      end
    end
  end

   devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    
  belongs_to :customer

  

  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  validates :customer_id, :item_id, :quantity, presence: true
  validates :quantity, numericality: { only_integer: true }
  
   def subtotal
    item.add_tax_price*quantity
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end
	
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :orders, through: :order_items
  has_many :order_items
  
  has_one_attached :image
  validates :genre_id, :name, :price, presence: true
	validates :body, length: { maximum: 200 }, presence: true
	validates :price, numericality: { only_integer: true }

def add_tax_price
  (self.price * 1.10).round
end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy #order_itemになってました

  #enum payment_method ["クレジットカード", "銀行振込"] #0=クレカ、1=銀行振り込み
  enum pay_method: { credit_card: 0, transfer: 1 }

  enum order_status: {
     "入金待ち": 0,
     "入金確認": 1,
     "製作中": 2,
     "発送準備中": 3,
     "発送済み": 4
  }


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  #ApplicationRecorhasになってました
  belongs_to :order #belongs_to :ordrerになってました
  belongs_to :item

enum creat_status: { #本来、create_statusです
  "着手不可":0,
  "制作待ち":1,
  "製作中":2,
  "制作完了":3,
}

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
   before_action :authenticate_admin!
   
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def create
   @genre = Genre.new(genre_params)
   @genres = Genre.all
   if @genre.save
      redirect_to admin_genres_path
   else
      render :index
   end
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def create
   @item = Item.new(item_params)
   @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def update
   @item = Item.find(params[:id])
   @genres = Genre.all
   if @item.update(item_params)
    redirect_to admin_item_path(@item)
   else
    render :edit
   end
  end

  private
  def item_params
   params.require(:item).permit(:name, :body, :genre_id, :price, :image, :sale_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_kana_name, :last_kana_name, :postcode, :address, :phone_number])
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(model.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom">
    <nav class="navar bg-dark text-white text-center">@team AQUA</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="headber">
  <nav class="navar bg-light">
    <div class="container">
      <div class="row">
       <div class="col-3">
        <% if admin_signed_in? %>
         <%= link_to admin_orders_path do %><i class="fas fa-home"></i><% end %>
        <% else %>
         <%= link_to root_path do %><i class="fas fa-home"></i><% end %>
        <% end %>
       </div>

       <div class="col-3">
        <% if customer_signed_in? %>
       <div>ようこそ、<%= current_customer.last_name %>さん！</div>
        <% end %>
       </div>


       <div class="col-6">
        <% if customer_signed_in? %>
         <%= link_to "マイページ", customers_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "商品一覧", items_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "カート", cart_items_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-sm btn-outline-dark" %>
        <% elsif admin_signed_in? %>
         <%= link_to "商品一覧", admin_items_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "会員一覧", admin_customers_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "注文履歴一覧", admin_orders_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-sm btn-outline-dark" %>
        <% else %>
         <%= link_to "About", about_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "商品一覧", items_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-sm btn-outline-dark" %>
         <%= link_to "ログイン", new_customer_session_path, class: "btn btn-sm btn-outline-dark" %>
        <% end %>
       </div>
       
      </div>
     </div>
   </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>